### ISSUE TITLE
mobile scrolling issue

### ISSUE THREAD

**Issue by jfols** [ride-cbus/ride-cbus#14]
this can't be right... @kevinmack18 halp!

main.css

```
html.ios, html.ios body {
    height: 100% !important;
}
```

**Comment by jfols** [comment]
Maybe something like this, `2em` is assumed height of top menu bar.

```
/* calc(100vh - 2em); */
#map {
  height: 100%vh;
  width: 100%;
}
```

**Comment by kevinmack18** [comment]
#map {

height: calc(100vh - 2em); /*2em = height of nav*/

width: 100%;

}
